# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowderSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('standard_name', models.CharField(max_length=80)),
                ('_powder_diffrac', models.TextField(blank=True, db_column='data')),
            ],
        ),
    ]
